#lang racket
(define (qbrt x) 
  (define (qube x) (* x x x)) 
  (define (square x) (* x x)) 
  (define (qbrt-iter guess) 
    (define (good-enough?) 
      (< (abs (- (qube guess) x)) 0.0001)) 
    (define (improve) 
      (/ (+ (/ x (square guess)) 
            (* 2 guess)) 
         3)) 
    (if (good-enough?) 
        guess 
        (qbrt-iter (improve)))) 
  (qbrt-iter 1.0))